<a href="https://colab.research.google.com/github/skyhawker010501/credit-card-fraud-detection-with-python/blob/main/credit_card_fraud_detection_with_python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [2]:
# load a dataset towards pandas dataframe
cc_data = pd.read_csv('/content/creditcard.csv')

In [3]:
#print first five rows
cc_data.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0.0
1,0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0.0
2,1,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0.0
3,1,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0.0
4,2,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0.0

In [4]:
cc_data.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
1981,1524,-0.340622,1.132232,1.291494,0.062313,0.016387,-0.977070,0.723755,-0.074630,-0.396655,...,-0.262948,-0.688785,-0.010937,0.334061,-0.160025,0.071779,0.245128,0.098336,5.35,0.0
1982,1525,-1.842696,1.740641,0.861526,-0.856315,-0.655376,-0.842786,0.198563,0.602764,0.455595,...,-0.213609,-0.400617,0.030013,0.512611,-0.077087,0.286218,0.586012,0.352610,1.00,0.0
1983,1525,-0.480693,0.646091,1.577264,-0.084411,-0.305958,-0.534739,0.860346,-0.028569,-0.800705,...,0.121681,0.175190,0.035986,0.557665,-0.112301,0.337154,-0.015602,0.051504,80.70,0.0
1984,1525,-0.342132,1.091125,1.282729,0.068076,-0.022498,-0.996727,0.676304,-0.042250,-0.312036,...,-0.269850,-0.734148,-0.007354,0.319161,-0.179146,0.073683,0.241932,0.097139,3.59,0.0
1985,1526,-0.854343,1.382948,1.278665,2.914727,-0.183139,-0.349329,0.274566,0.435277,-1.576521,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
cc_data

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0.0
1,0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0.0
2,1,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0.0
3,1,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0.0
4,2,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1981,1524,-0.340622,1.132232,1.291494,0.062313,0.016387,-0.977070,0.723755,-0.074630,-0.396655,...,-0.262948,-0.688785,-0.010937,0.334061,-0.160025,0.071779,0.245128,0.098336,5.35,0.0
1982,1525,-1.842696,1.740641,0.861526,-0.856315,-0.655376,-0.842786,0.198563,0.602764,0.455595,...,-0.213609,-0.400617,0.030013,0.512611,-0.077087,0.286218,0.586012,0.352610,1.00,0.0
1983,1525,-0.480693,0.646091,1.577264,-0.084411,-0.305958,-0.534739,0.860346,-0.028569,-0.800705,...,0.121681,0.175190,0.035986,0.557665,-0.112301,0.337154,-0.015602,0.051504,80.70,0.0
1984,1525,-0.342132,1.091125,1.282729,0.068076,-0.022498,-0.996727,0.676304,-0.042250,-0.312036,...,-0.269850,-0.734148,-0.007354,0.319161,-0.179146,0.073683,0.241932,0.097139,3.59,0.0
1985,1526,-0.854343,1.382948,1.278665,2.914727,-0.183139,-0.349329,0.274566,0.435277,-1.576521,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
#dataset information
cc_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1986 entries, 0 to 1985
Data columns (total 31 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Time    1986 non-null   int64
 1   V1      1986 non-null   float64
 2   V2      1986 non-null   float64
 3   V3      1986 non-null   float64
 4   V4      1986 non-null   float64
 5   V5      1986 non-null   float64
 6   V6      1986 non-null   float64
 7   V7      1986 non-null   float64
 8   V8      1986 non-null   float64
 9   V9      1986 non-null   float64
 10  V10     1986 non-null   float64
 11  V11     1986 non-null   float64
 12  V12     1986 non-null   float64
 13  V13     1986 non-null   float64
 14  V14     1985 non-null   float64
 15  V15     1985 non-null   float64
 16  V16     1985 non-null   float64
 17  V17     1985 non-null   float64
 18  V18     1985 non-null   float64
 19  V19     1985 non-null   float64
 20  V20     1985 non-null   float64
 21  V21     1985 non-null   float64
 22  V22     1985 non-null   float64
 23  V23     1985 non-null   float64
 24  V24     1985 non-null   float64
 25  V25     1985 non-null   float64
 26  V26     1985 non-null   float64
 27  V27     1985 non-null   float64
 28  V28     1985 non-null   float64
 29  Amount  1985 non-null   float64
 30  Class   1985 non-null   float64
dtypes: float64(30), int64(1)
memory usage: 481.1 KB

In [7]:
# disribution of legit and fraud transaction
cc_data['Class'].value_counts()

0.0    1983
1.0       2
Name: Class, dtype: int64

In [8]:
#this dataset is highly unbalanced
#0--> Normal Transaction and 1-->Fraudlent Transaction

#seprating the data for analysis
legal = cc_data[cc_data.Class==0]
fraud = cc_data[cc_data.Class==1]

In [9]:
print(legal.shape)
print(fraud.shape)

(1983, 31)
(2, 31)

In [10]:
#statical measure of data
legal.Amount.describe()
#fraud.Amount.describe()

count    1983.000000
mean       68.404892
std       241.572682
min         0.000000
25%         4.950000
50%        15.090000
75%        63.285000
max      7712.430000
Name: Amount, dtype: float64

In [11]:
fraud.Amount.describe()

count      2.000000
mean     264.500000
std      374.059487
min        0.000000
25%      132.250000
50%      264.500000
75%      396.750000
max      529.000000
Name: Amount, dtype: float64

In [12]:
#Compare the value of both transaction
cc_data.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0.0,760.974786,-0.281494,0.267200,0.848906,0.146804,-0.077904,0.051713,0.139533,-0.059771,0.014492,...,0.056618,-0.012217,-0.144666,-0.043548,0.013865,0.108318,0.049441,0.027220,-0.001966,68.404892
1.0,439.000000,-2.677884,-0.602658,-0.260694,3.143275,0.418809,-1.245684,-1.105907,0.661932,-1.520521,...,1.114625,0.589464,0.200214,0.455377,0.013198,0.162159,0.016239,0.004186,-0.053756,264.500000

In [13]:
#Under Sampling
#-->means a build sample dataset contaning similar distrubution of legal and fraud transation
legal_sample = legal.sample(n=156)

In [14]:
new_dataset = pd.concat([legal_sample,fraud],axis=0)

In [15]:
new_dataset['Class'].value_counts()

0.0    156
1.0      2
Name: Class, dtype: int64

In [16]:
new_dataset.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0.0,790.826923,-0.175581,0.342039,0.878733,0.188028,-0.070011,0.066769,0.084184,-0.025883,-0.089942,...,0.039858,0.022488,-0.142007,-0.044315,0.052707,0.099144,0.071491,0.064658,0.028777,52.575385
1.0,439.000000,-2.677884,-0.602658,-0.260694,3.143275,0.418809,-1.245684,-1.105907,0.661932,-1.520521,...,1.114625,0.589464,0.200214,0.455377,0.013198,0.162159,0.016239,0.004186,-0.053756,264.500000

In [17]:
x = new_dataset.drop(columns = 'Class', axis=1)
y = new_dataset['Class']

In [18]:
print(x)
print(y)

      Time        V1        V2        V3        V4        V5        V6  \
1662  1288  1.052661 -0.468487  1.045052  0.725626 -1.014531  0.206781
1476  1153 -1.933394  0.362694  0.600302 -0.276266 -1.241034 -0.439342
1796  1396 -1.032816  0.641670  1.421100 -0.714244  0.077135 -0.349414
762    572  1.063195 -1.156247 -0.814094 -0.462132  1.137835  3.909057
644    488  0.986168 -0.550923  1.140934  0.757901 -1.038890  0.476782
...    ...       ...       ...       ...       ...       ...       ...
1840  1428 -1.842595  1.750624  0.864391 -0.857654 -0.643078 -0.839508
1745  1351  1.076106 -0.986371  0.268873 -0.032871 -1.061800 -0.150792
1878  1447 -1.402639  1.349529  0.750455 -0.923129 -0.061847 -0.080808
541    406 -2.312227  1.951992 -1.609851  3.997906 -0.522188 -1.426545
623    472 -3.043541 -3.157307  1.088463  2.288644  1.359805 -1.064823

            V7        V8        V9  ...       V20       V21       V22  \
1662 -0.726219  0.281938  0.833684  ... -0.026672 -0.038833 -0.127184
1476  0.500471  0.805716 -0.431321  ... -0.387045 -0.005164 -0.201480
1796  0.503000  0.144358  0.240660  ... -0.157567 -0.181256 -0.388226
762  -1.116745  0.920514 -0.600150  ... -0.112384 -0.205083 -0.434832
644  -0.837096  0.433228  0.896975  ... -0.106760  0.003400 -0.001184
...        ...       ...       ...  ...       ...       ...       ...
1840  0.207911  0.594936  0.434731  ...  0.377951 -0.212025 -0.389332
1745 -0.446514  0.029837 -0.682958  ... -0.288768 -0.500738 -1.168443
1878  0.217158  0.650295  0.191454  ...  0.168678 -0.228203 -0.475329
541  -2.537387  1.391657 -2.770089  ...  0.126911  0.517232 -0.035049
623   0.325574 -0.067794 -0.270953  ...  2.102339  0.661696  0.435477

           V23       V24       V25       V26       V27       V28  Amount
1662 -0.059162  0.028137  0.214803  0.316555 -0.004292  0.021510   64.99
1476  0.369574  0.567641 -0.164117  0.306871 -0.163808 -0.269050  158.00
1796 -0.051280 -0.005437 -0.006163  0.368106  0.041036  0.116294    5.00
762  -0.220055  0.991996  0.631624 -0.223179  0.052542  0.053525  158.00
644   0.017652  0.026666  0.078602  0.328056  0.008762  0.020131   64.99
...        ...       ...       ...       ...       ...       ...     ...
1840  0.028359  0.516384 -0.072425  0.285756  0.586913  0.352906    1.00
1745 -0.055652 -0.006054  0.248210  0.402263 -0.041972  0.022888  138.00
1878 -0.204644 -0.486190  0.203751  0.424468  0.362865  0.202213    5.00
541  -0.465211  0.320198  0.044519  0.177840  0.261145 -0.143276    0.00
623   1.375966 -0.293803  0.279798 -0.145362 -0.252773  0.035764  529.00

[158 rows x 30 columns]
1662    0.0
1476    0.0
1796    0.0
762     0.0
644     0.0
       ...
1840    0.0
1745    0.0
1878    0.0
541     1.0
623     1.0
Name: Class, Length: 158, dtype: float64

In [19]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2, stratify = y, random_state =2)

In [20]:
print(x.shape,x_train.shape,x_test.shape)

(158, 30) (126, 30) (32, 30)

Model Training

In [21]:
#logistic regression
model = LogisticRegression()

In [22]:
model.fit(x_train,y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [23]:
#accuracy prediction
x_train_prediction = model.predict(x_train)
training_data_accuracy = accuracy_score(x_train_prediction,y_train)
print(training_data_accuracy)

1.0

In [24]:
x_test_prediction = model.predict(x_test)
testing_data_accuracy = accuracy_score(x_test_prediction,y_test)
print(testing_data_accuracy)

0.9375